name: Unity WebGL CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode and install Unity license
        run: |
          echo "${{ secrets.UNITY_LICENSE }}" | base64 -d > Unity_v2022.x.ulf
          mkdir -p ~/.local/share/unity3d/Unity/License
          mv Unity_v2022.x.ulf ~/.local/share/unity3d/Unity/License/

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build WebGL
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.5f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}  # still required to satisfy the builder

      - name: Upload WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WebGL Build
        uses: actions/download-artifact@v4
        with:
          name: WebGLBuild
          path: webgl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webgl
