name: Unity WebGL CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build WebGL with GameCI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@v3
        with:
          unityVersion: 6000.0.42f1 # your Unity 6 version

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 6000.0.42f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build WebGL
        uses: game-ci/unity-actions/build@v3
        with:
          targetPlatform: WebGL

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebGLBuild
          path: build/WebGL

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download WebGL build
        uses: actions/download-artifact@v3
        with:
          name: WebGLBuild
          path: webgl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webgl
